name = "oneday"
main = ".output/server/index.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]
keep_vars = true

[assets]
binding = "ASSETS"
directory = ".output/public"

[[kv_namespaces]]
binding = "REGISTRY"
id = "623d8b76dab74f37b63d66cbe55588c4"

[observability]

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
